services:
  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=macampos
      - MYSQL_PASSWORD=1234
    networks:
      - inception
    restart: always

  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    container_name: wp-php
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=macampos
      - WORDPRESS_DB_PASSWORD=1234
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - inception
    restart: always

  nginx:
    build: requirements/nginx/.
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_files:/var/www/html:ro
      - ./requirements/nginx/ssl:/etc/nginx/ssl
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
  wordpress_files:

networks:
  inception:
    driver: bridge
