services:
  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    .env: ../.env
    environment:
      - MYSQL_ROOT_PASSWORD={$MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE={$MYSQL_DATABASE}
      - MYSQL_USER={$MYSQL_USER}
      - MYSQL_PASSWORD={$MYSQL_PASSWORD}
    networks:
      - inception
    restart: always

  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    container_name: wp-php
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    .env: ../.env
    environment:
      - WORDPRESS_DB_HOST={$WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER={$WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD={$WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME={$WORDPRESS_DB_NAME}
    networks:
      - inception
    restart: always

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
  wordpress_files:
    driver: local
    driver opts:
      type: none
      o: bind
      device: ~data/wordpress_files

networks:
  inception:
    driver: bridge
