
services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    # volumes:
    #   - mariadb_data:/var/lib/mysql
    # network:
    #   - inception
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    # volumes:
    #   - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    # network:
    #   - inception
    restart: always
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    # volumes:
    #   - wordpress_files:/var/www/html:ro
      # - ./requirements/nginx/ssl:/etc/nginx/ssl
    # network:
    #   - inception
    restart: always
# volumes:
#   mariadb_data:
#   Wordpress_files:

networks:
  inception: