FROM debian:bullseye

RUN apt-get update && apt-get install -y mariadb-server && rm -rf /var/lib/apt/lists/*

COPY /tools/50-server.cnf /etc/mysql/mariadb.conf.d/

RUN chmod +x /bin/scropt.sh

RUN mkdir -p /run/mysqld && chown mysql:mysql /run/mysqld

USER mysql

CMD ["mysqld"]
