FROM debian:bullseye

RUN apt-get update && apt-get install -y mariadb-server && rm -rf /var/lib/apt/lists/*

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/

RUN mkdir -p /run/mysqld && chown mysql:mysql /run/mysqld

USER mysql

CMD ["mysqld"]
