FROM debian:bullseye

RUN apt-get update && apt-get install -y apt-transport-https lsb-release ca-certificates wget gnupg2 \
  && wget -qO /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
  && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list \
  && apt-get update \
  && apt-get install -y wget unzip php8.2-fpm php8.2-mysql \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /run/php

COPY www.conf /etc/php/8.2/fpm/pool.d/

CMD ["php-fpm8.2", "-F"]

