FROM debian:bullseye

RUN apt-get update && apt-get install -y \
    ca-certificates wget gnupg2 lsb-release curl unzip \
 && wget -qO /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
 && echo "deb https://packages.sury.org/php/ $(. /etc/os-release && echo $VERSION_CODENAME) main" > /etc/apt/sources.list.d/php.list \
 && apt-get update \
 && apt-get install -y php8.2-fpm php8.2-mysql \
 && rm -rf /var/lib/apt/lists/*


RUN mkdir -p /run/php

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

RUN mkdir -p /var/www/html \
    && chown -R www-data:www-data /var/www/html

COPY /tools/www.conf /etc/php/8.2/fpm/pool.d/

COPY ./tools/wordpress.sh /bin

RUN chmod +x /bin/wordpress.sh

ENTRYPOINT ["/bin/wordpress.sh"]

CMD ["php-fpm8.2", "-F"]