
FROM debian:bullseye

RUN apt-get update && apt-get install -y nginx && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -newkey rsa:2048 -nodes -keyout /etc/nginx/ssl/nginx.key -x509 -out /etc/nginx/ssl/nginx.crt && ls -alh /etc/nginx/ssl

WORKDIR /etc/nginx/

COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
